"use client";

import { useState, useEffect, useCallback, useRef } from "react";

const PAD = 10;
const TW = 360;
const OVERLAY = "rgba(3, 5, 16, 0.88)";

const STEPS = [
  {
    target: null,
    pos: "center" as const,
    label: "MISSION BRIEFING",
    title: "Welcome to Hack Orbit",
    body: "This guided tour walks you through every panel of the AI Mission Intelligence Dashboard — what each component does, what operators look for, and why it matters. Click Next or use arrow keys to navigate.",
  },
  {
    target: "[data-tour='health-score']",
    pos: "right" as const,
    label: "HEALTH SCORE INDEX",
    title: "Spacecraft Health Score (HSI)",
    body: "A composite score (0–100) computed by our XGBoost model trained on real satellite telemetry datasets. Below 70 triggers elevated monitoring; below 50 demands immediate operator action. The ring color shifts green → yellow → red as health degrades.",
  },
  {
    target: "[data-tour='mission-brief']",
    pos: "left" as const,
    label: "AI EXECUTIVE SUMMARY",
    title: "Mission Brief",
    body: "Real-time operational narrative generated by the AI Copilot. Synthesizes health score, live telemetry, space weather, and debris data into a plain-language situational brief — the kind a flight director delivers to mission control before every shift.",
  },
  {
    target: "[data-tour='telemetry']",
    pos: "right" as const,
    label: "LIVE SENSOR DATA",
    title: "Telemetry Panel",
    body: "Eight real-time sensor channels covering power, thermal, attitude control, and communication subsystems. Values update every 1.5 seconds with simulated sensor noise. Directional arrows (↑↓) show the trend since the last reading; color flags deviation from nominal.",
  },
  {
    target: "[data-tour='weather']",
    pos: "bottom" as const,
    label: "SPACE ENVIRONMENT",
    title: "Space Weather",
    body: "Live geomagnetic conditions from NOAA. The Kp index (0–9) measures global disturbance intensity. Above 5 is a storm — it degrades GPS navigation, increases radiation exposure to sensitive electronics, and accelerates orbital decay through atmospheric drag.",
  },
  {
    target: "[data-tour='debris']",
    pos: "left" as const,
    label: "COLLISION RISK",
    title: "Debris Conjunction Panel",
    body: "Tracked objects from the Space Surveillance Network catalog approaching our orbital trajectory. Each row shows the object ID, estimated miss distance, and risk tier. A critical conjunction triggers a 24-hour window to evaluate and execute an avoidance maneuver.",
  },
  {
    target: "[data-tour='forecast']",
    pos: "top" as const,
    label: "PREDICTIVE MODELING",
    title: "7-Day Health Forecast",
    body: "ML projection of spacecraft health over the next 7 days, based on current telemetry trends and environmental inputs. Shifts operations from reactive to proactive — operators anticipate degradation and schedule maintenance before a failure occurs.",
  },
  {
    target: "[data-tour='copilot']",
    pos: "top" as const,
    label: "AI DECISION SUPPORT",
    title: "AI Mission Copilot",
    body: "Ask any operational question in natural language — current risk level, maneuver recommendations, subsystem diagnostics, or incident analysis. Backed by multiple LLM providers with a deterministic fallback that always responds. Generates formal incident reports on demand.",
  },
  {
    target: "[data-tour='scenario-switcher']",
    pos: "bottom" as const,
    label: "SCENARIO CONTROL",
    title: "Scenario Switcher",
    body: "Instantly inject one of five pre-configured mission scenarios. Each propagates realistic data across every panel simultaneously — health score, telemetry, weather, and debris — letting you observe how the system responds to different operational states.",
  },
  {
    target: "[data-tour='sim-button']",
    pos: "bottom" as const,
    label: "TRAINING MODE",
    title: "Mission Simulation Center",
    body: "Launches a fullscreen guided walkthrough of all five scenarios with structured AI assessments for each. Designed for operator training, mission readiness review, and demonstrating decision-support capabilities — fully functional even without backend connectivity.",
  },
];

interface ERect { l: number; t: number; w: number; h: number }

function useWindowSize() {
  const [size, setSize] = useState({ w: 1440, h: 900 });
  useEffect(() => {
    const set = () => setSize({ w: window.innerWidth, h: window.innerHeight });
    set();
    window.addEventListener("resize", set);
    return () => window.removeEventListener("resize", set);
  }, []);
  return size;
}

export default function DashboardTour({ onClose }: { onClose: () => void }) {
  const [step, setStep] = useState(0);
  const [eRect, setERect] = useState<ERect | null>(null);
  const win = useWindowSize();

  const cur = STEPS[step];
  const isFirst = step === 0;
  const isLast = step === STEPS.length - 1;

  const next = useCallback(() => (isLast ? onClose() : setStep((s) => s + 1)), [isLast, onClose]);
  const prev = useCallback(() => { if (!isFirst) setStep((s) => s - 1); }, [isFirst]);

  // Drag state for the tooltip card
  const [drag, setDrag] = useState({ x: 0, y: 0 });
  const [dragging, setDragging] = useState(false);
  const dragOrigin = useRef({ mx: 0, my: 0, ox: 0, oy: 0 });

  // Reset drag offset when step changes
  useEffect(() => { setDrag({ x: 0, y: 0 }); }, [step]);

  useEffect(() => {
    if (!dragging) return;
    const move = (e: MouseEvent) => {
      setDrag({
        x: dragOrigin.current.ox + e.clientX - dragOrigin.current.mx,
        y: dragOrigin.current.oy + e.clientY - dragOrigin.current.my,
      });
    };
    const up = () => setDragging(false);
    window.addEventListener("mousemove", move);
    window.addEventListener("mouseup", up);
    return () => { window.removeEventListener("mousemove", move); window.removeEventListener("mouseup", up); };
  }, [dragging]);

  const startDrag = (e: React.MouseEvent) => {
    e.preventDefault();
    dragOrigin.current = { mx: e.clientX, my: e.clientY, ox: drag.x, oy: drag.y };
    setDragging(true);
  };

  // Measure + scroll target into view
  useEffect(() => {
    if (!cur.target) { setERect(null); return; }
    const el = document.querySelector(cur.target) as HTMLElement | null;
    if (!el) { setERect(null); return; }
    el.scrollIntoView({ behavior: "smooth", block: "nearest" });
    const t = setTimeout(() => {
      const r = el.getBoundingClientRect();
      setERect({ l: r.left - PAD, t: r.top - PAD, w: r.width + PAD * 2, h: r.height + PAD * 2 });
    }, 350);
    return () => clearTimeout(t);
  }, [step, cur.target]);

  // Keyboard nav
  useEffect(() => {
    const fn = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
      if (e.key === "ArrowRight" || e.key === "Enter") next();
      if (e.key === "ArrowLeft") prev();
    };
    window.addEventListener("keydown", fn);
    return () => window.removeEventListener("keydown", fn);
  }, [next, prev, onClose]);

  // Tooltip base position (without drag)
  const getBaseTipStyle = (): React.CSSProperties => {
    if (!eRect || cur.pos === "center") {
      return { position: "fixed", top: win.h / 2 - 140, left: win.w / 2 - TW / 2, width: TW };
    }
    const gap = 20;
    const cx = eRect.l + eRect.w / 2;
    const cy = eRect.t + eRect.h / 2;
    const s: React.CSSProperties = { position: "fixed", width: TW };
    if (cur.pos === "right") {
      s.left = Math.min(eRect.l + eRect.w + gap, win.w - TW - 12);
      s.top = Math.max(12, Math.min(cy - 130, win.h - 310));
    } else if (cur.pos === "left") {
      s.left = Math.max(12, eRect.l - TW - gap);
      s.top = Math.max(12, Math.min(cy - 130, win.h - 310));
    } else if (cur.pos === "bottom") {
      s.left = Math.max(12, Math.min(cx - TW / 2, win.w - TW - 12));
      s.top = Math.min(eRect.t + eRect.h + gap, win.h - 310);
    } else {
      s.left = Math.max(12, Math.min(cx - TW / 2, win.w - TW - 12));
      s.top = Math.max(12, eRect.t - 290 - gap);
    }
    return s;
  };

  const base = getBaseTipStyle();
  const tipStyle: React.CSSProperties = {
    ...base,
    left: (base.left as number) + drag.x,
    top:  (base.top  as number) + drag.y,
  };

  const overlayStyle: React.CSSProperties = { position: "fixed", background: OVERLAY, zIndex: 9990, cursor: "pointer" };

  return (
    <>
      {/* ── Overlay: 4 panels surrounding spotlight (or full screen on welcome) ── */}
      {!eRect ? (
        // Welcome step — full-screen dark overlay
        <div style={{ ...overlayStyle, inset: 0 }} onClick={next} />
      ) : (
        <>
          {/* Top */}
          <div style={{ ...overlayStyle, top: 0, left: 0, right: 0, height: eRect.t }} onClick={next} />
          {/* Bottom */}
          <div style={{ ...overlayStyle, top: eRect.t + eRect.h, left: 0, right: 0, bottom: 0 }} onClick={next} />
          {/* Left */}
          <div style={{ ...overlayStyle, top: eRect.t, left: 0, width: eRect.l, height: eRect.h }} onClick={next} />
          {/* Right */}
          <div style={{ ...overlayStyle, top: eRect.t, left: eRect.l + eRect.w, right: 0, height: eRect.h }} onClick={next} />

          {/* Spotlight ring */}
          <div
            style={{
              position: "fixed",
              top: eRect.t, left: eRect.l, width: eRect.w, height: eRect.h,
              zIndex: 9991,
              borderRadius: 10,
              border: "1.5px solid rgba(96, 165, 250, 0.8)",
              boxShadow: "0 0 16px rgba(96, 165, 250, 0.25), inset 0 0 0 1px rgba(96,165,250,0.15)",
              pointerEvents: "none",
              transition: "top 0.3s ease, left 0.3s ease, width 0.3s ease, height 0.3s ease",
            }}
          />
        </>
      )}

      {/* ── Tooltip card ─────────────────────────────────────────────────────── */}
      <div
        style={{ ...tipStyle, zIndex: 9995, cursor: dragging ? "grabbing" : "default" }}
        className="rounded-xl border border-blue-800/60 bg-[#0d1224] shadow-2xl overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Drag handle — blue accent line doubles as grab zone */}
        <div
          onMouseDown={startDrag}
          style={{ cursor: dragging ? "grabbing" : "grab" }}
          className="h-5 bg-gradient-to-r from-transparent via-blue-500/50 to-transparent flex items-center justify-center"
          title="Drag to move"
        >
          <span className="text-slate-700 text-xs select-none">⠿⠿⠿</span>
        </div>

        <div className="px-5 pb-5">

          {/* Progress dots */}
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-1">
              {STEPS.map((_, i) => (
                <button
                  key={i}
                  onClick={() => setStep(i)}
                  className={`rounded-full transition-all duration-200 ${
                    i === step
                      ? "w-5 h-1.5 bg-blue-400"
                      : i < step
                      ? "w-1.5 h-1.5 bg-blue-800"
                      : "w-1.5 h-1.5 bg-slate-700 hover:bg-slate-500"
                  }`}
                />
              ))}
            </div>
            <button
              onClick={onClose}
              className="text-xs text-slate-600 hover:text-slate-400 transition-colors font-mono uppercase tracking-widest"
            >
              skip
            </button>
          </div>

          {/* Content */}
          <p className="text-xs font-mono uppercase tracking-[0.18em] text-blue-500 mb-1.5">
            {cur.label}
          </p>
          <h3 className="text-sm font-bold text-slate-100 mb-2 leading-snug">
            {cur.title}
          </h3>
          <p className="text-xs text-slate-400 leading-relaxed mb-4">
            {cur.body}
          </p>

          {/* Nav */}
          <div className="flex items-center justify-between">
            <button
              onClick={prev}
              disabled={isFirst}
              className="px-3 py-1.5 text-xs text-slate-500 hover:text-slate-300 disabled:opacity-0 transition-all font-mono"
            >
              ← prev
            </button>
            <span className="text-xs text-slate-600 font-mono tabular-nums">
              {step + 1} / {STEPS.length}
            </span>
            <button
              onClick={next}
              className="px-4 py-1.5 rounded-md bg-blue-600 hover:bg-blue-500 text-xs text-white font-semibold transition-all duration-150"
            >
              {isLast ? "Finish Tour" : "Next →"}
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
